"""add hp_zones and effects to location_characters

Revision ID: 389f6f92f5bc
Revises: 59d2f2b9e43a
Create Date: 2026-05-27 00:36:44.891195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389f6f92f5bc'
down_revision = '59d2f2b9e43a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location_characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hp_zones', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('effects', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location_characters', schema=None) as batch_op:
        batch_op.drop_column('effects')
        batch_op.drop_column('hp_zones')

    # ### end Alembic commands ###
