"""Add locations and related tables

Revision ID: 59d2f2b9e43a
Revises: 6f1c53a28d3d
Create Date: 2026-04-22 12:11:49.773706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d2f2b9e43a'
down_revision = '6f1c53a28d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lobby_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('grid_width', sa.Integer(), nullable=False),
    sa.Column('grid_height', sa.Integer(), nullable=False),
    sa.Column('tiles_data', sa.JSON(), nullable=False),
    sa.Column('world_tile_x', sa.Integer(), nullable=False),
    sa.Column('world_tile_z', sa.Integer(), nullable=False),
    sa.Column('world_radius', sa.Integer(), nullable=True),
    sa.Column('spawn_points', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('pos_x', sa.Integer(), nullable=False),
    sa.Column('pos_y', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_action', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['lobby_characters.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('tile_x', sa.Integer(), nullable=False),
    sa.Column('tile_y', sa.Integer(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_objects')
    op.drop_table('location_characters')
    op.drop_table('locations')
    # ### end Alembic commands ###
