"""Unified item templates

Revision ID: 6f1c53a28d3d
Revises: a08d95e41a71
Create Date: 2026-03-20 00:35:58.006170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f1c53a28d3d'
down_revision = 'a08d95e41a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('item_class', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('compatible_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_templates_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_templates_subcategory'), ['subcategory'], unique=False)

    op.create_table('lobby_item_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lobby_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('item_class', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('compatible_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('lobby_consumable_templates')
    op.drop_table('artifact_templates')
    op.drop_table('lobby_gas_mask_templates')
    op.drop_table('special_trait_templates')
    op.drop_table('backpack_templates')
    op.drop_table('consumable_templates')
    op.drop_table('lobby_melee_weapon_templates')
    op.drop_table('lobby_armor_templates')
    op.drop_table('lobby_modification_templates')
    op.drop_table('lobby_detector_templates')
    op.drop_table('lobby_special_trait_templates')
    op.drop_table('armor_templates')
    op.drop_table('lobby_artifact_templates')
    op.drop_table('melee_weapon_templates')
    op.drop_table('detector_templates')
    op.drop_table('organization_templates')
    op.drop_table('lobby_organization_templates')
    op.drop_table('lobby_container_templates')
    op.drop_table('container_templates')
    op.drop_table('lobby_backpack_templates')
    op.drop_table('modification_templates')
    op.drop_table('lobby_background_templates')
    op.drop_table('gas_mask_templates')
    op.drop_table('lobby_weapon_templates')
    op.drop_table('background_templates')
    op.drop_table('crafting_material_templates')
    op.drop_table('lobby_helmet_templates')
    op.drop_table('lobby_effect_templates')
    op.drop_table('weapon_templates')
    op.drop_table('effect_templates')
    op.drop_table('lobby_crafting_material_templates')
    op.drop_table('helmet_templates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helmet_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('max_durability', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('material', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accuracy_penalty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ergonomics_penalty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('charisma_bonus', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('protection', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('helmet_templates_pkey'))
    )
    op.create_table('lobby_crafting_material_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lobby_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('lobby_crafting_material_templates_created_by_fkey')),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('lobby_crafting_material_templates_lobby_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lobby_crafting_material_templates_pkey'))
    )
    op.create_table('effect_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('effect_templates_pkey'))
    )
    op.create_table('weapon_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accuracy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('noise', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ammo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('range', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ergonomics', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('burst', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('damage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('durability', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fire_rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('caliber', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('magazine_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('weapon_templates_pkey'))
    )
    op.create_table('lobby_effect_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lobby_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('lobby_effect_templates_created_by_fkey')),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('lobby_effect_templates_lobby_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lobby_effect_templates_pkey'))
    )
    op.create_table('lobby_helmet_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lobby_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('max_durability', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('material', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accuracy_penalty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ergonomics_penalty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('charisma_bonus', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('protection', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('lobby_helmet_templates_created_by_fkey')),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('lobby_helmet_templates_lobby_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lobby_helmet_templates_pkey'))
    )
    op.create_table('crafting_material_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('crafting_material_templates_pkey'))
    )
    op.create_table('background_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pluses', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('minuses', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('skill_bonuses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('background_templates_pkey'))
    )
    op.create_table('lobby_weapon_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lobby_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accuracy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('noise', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ammo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('range', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ergonomics', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('burst', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('damage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('durability', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fire_rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('caliber', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('magazine_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('lobby_weapon_templates_created_by_fkey')),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('lobby_weapon_templates_lobby_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lobby_weapon_templates_pkey'))
    )
    op.create_table('gas_mask_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('max_durability', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filter_capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('material', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accuracy_penalty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ergonomics_penalty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('charisma_bonus', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('protection', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('gas_mask_templates_pkey'))
    )
    op.create_table('lobby_background_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lobby_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pluses', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('minuses', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('skill_bonuses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('lobby_background_templates_created_by_fkey')),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('lobby_background_templates_lobby_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lobby_background_templates_pkey'))
    )
    op.create_table('modification_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('effect', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('modification_templates_pkey'))
    )
    op.create_table('lobby_backpack_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lobby_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('weight_reduction', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('lobby_backpack_templates_created_by_fkey')),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('lobby_backpack_templates_lobby_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lobby_backpack_templates_pkey'))
    )
    op.create_table('container_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('effect', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('container_templates_pkey'))
    )
    op.create_table('lobby_container_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lobby_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('effect', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('lobby_container_templates_created_by_fkey')),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('lobby_container_templates_lobby_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lobby_container_templates_pkey'))
    )
    op.create_table('lobby_organization_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lobby_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('lobby_organization_templates_created_by_fkey')),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('lobby_organization_templates_lobby_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lobby_organization_templates_pkey'))
    )
    op.create_table('organization_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('organization_templates_pkey'))
    )
    op.create_table('detector_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('bonus', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('detector_templates_pkey'))
    )
    op.create_table('melee_weapon_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('damage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('durability', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('melee_weapon_templates_pkey'))
    )
    op.create_table('lobby_artifact_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lobby_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('effect', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('lobby_artifact_templates_created_by_fkey')),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('lobby_artifact_templates_lobby_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lobby_artifact_templates_pkey'))
    )
    op.create_table('armor_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('max_durability', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('material', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('movement_penalty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('container_slots', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('protection', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('armor_templates_pkey'))
    )
    op.create_table('lobby_special_trait_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lobby_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('effect', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('lobby_special_trait_templates_created_by_fkey')),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('lobby_special_trait_templates_lobby_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lobby_special_trait_templates_pkey'))
    )
    op.create_table('lobby_detector_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lobby_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('bonus', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('lobby_detector_templates_created_by_fkey')),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('lobby_detector_templates_lobby_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lobby_detector_templates_pkey'))
    )
    op.create_table('lobby_modification_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lobby_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('effect', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('lobby_modification_templates_created_by_fkey')),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('lobby_modification_templates_lobby_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lobby_modification_templates_pkey'))
    )
    op.create_table('lobby_armor_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lobby_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('max_durability', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('material', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('movement_penalty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('container_slots', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('protection', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('lobby_armor_templates_created_by_fkey')),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('lobby_armor_templates_lobby_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lobby_armor_templates_pkey'))
    )
    op.create_table('lobby_melee_weapon_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lobby_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('damage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('durability', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('lobby_melee_weapon_templates_created_by_fkey')),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('lobby_melee_weapon_templates_lobby_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lobby_melee_weapon_templates_pkey'))
    )
    op.create_table('consumable_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('effect', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('consumable_templates_pkey'))
    )
    op.create_table('backpack_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('weight_reduction', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('backpack_templates_pkey'))
    )
    op.create_table('special_trait_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('effect', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('special_trait_templates_pkey'))
    )
    op.create_table('lobby_gas_mask_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lobby_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('max_durability', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filter_capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('material', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accuracy_penalty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ergonomics_penalty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('charisma_bonus', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('protection', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('lobby_gas_mask_templates_created_by_fkey')),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('lobby_gas_mask_templates_lobby_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lobby_gas_mask_templates_pkey'))
    )
    op.create_table('artifact_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('effect', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('artifact_templates_pkey'))
    )
    op.create_table('lobby_consumable_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lobby_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('effect', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('lobby_consumable_templates_created_by_fkey')),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], name=op.f('lobby_consumable_templates_lobby_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lobby_consumable_templates_pkey'))
    )
    op.drop_table('lobby_item_templates')
    with op.batch_alter_table('item_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_templates_subcategory'))
        batch_op.drop_index(batch_op.f('ix_item_templates_category'))

    op.drop_table('item_templates')
    # ### end Alembic commands ###
