"""add color to user

Revision ID: 749bf62128de
Revises: 95e95ce809ed
Create Date: 2026-07-12 17:56:18.493956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749bf62128de'
down_revision = '95e95ce809ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
