"""add controlled_by to location_characters

Revision ID: 95e95ce809ed
Revises: 389f6f92f5bc
Create Date: 2026-07-12 16:49:28.691744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e95ce809ed'
down_revision = '389f6f92f5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location_characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('controlled_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['controlled_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location_characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('controlled_by')

    # ### end Alembic commands ###
