"""Backpack weight reduction

Revision ID: a08d95e41a71
Revises: 3e4cc6614557
Create Date: 2026-03-15 12:43:58.821158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a08d95e41a71'
down_revision = '3e4cc6614557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backpack_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_reduction', sa.Integer(), nullable=True))

    with op.batch_alter_table('lobby_backpack_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_reduction', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lobby_backpack_templates', schema=None) as batch_op:
        batch_op.drop_column('weight_reduction')

    with op.batch_alter_table('backpack_templates', schema=None) as batch_op:
        batch_op.drop_column('weight_reduction')

    # ### end Alembic commands ###
