"""add templates

Revision ID: ba0b8f798bc3
Revises: f60d114a4ae4
Create Date: 2026-03-13 16:36:12.040431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0b8f798bc3'
down_revision = 'f60d114a4ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('armor_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_durability', sa.Integer(), nullable=True),
    sa.Column('material', sa.String(length=50), nullable=True),
    sa.Column('movement_penalty', sa.Integer(), nullable=True),
    sa.Column('container_slots', sa.Integer(), nullable=True),
    sa.Column('protection', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifact_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('effect', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('background_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('pluses', sa.Text(), nullable=True),
    sa.Column('minuses', sa.Text(), nullable=True),
    sa.Column('skill_bonuses', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backpack_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumable_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('effect', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('container_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('effect', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crafting_material_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detector_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('effect_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gas_mask_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_durability', sa.Integer(), nullable=True),
    sa.Column('filter_capacity', sa.Integer(), nullable=True),
    sa.Column('material', sa.String(length=50), nullable=True),
    sa.Column('accuracy_penalty', sa.Integer(), nullable=True),
    sa.Column('ergonomics_penalty', sa.Integer(), nullable=True),
    sa.Column('charisma_bonus', sa.Integer(), nullable=True),
    sa.Column('protection', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('helmet_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_durability', sa.Integer(), nullable=True),
    sa.Column('material', sa.String(length=50), nullable=True),
    sa.Column('accuracy_penalty', sa.Integer(), nullable=True),
    sa.Column('ergonomics_penalty', sa.Integer(), nullable=True),
    sa.Column('charisma_bonus', sa.Integer(), nullable=True),
    sa.Column('protection', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('melee_weapon_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('damage', sa.Integer(), nullable=True),
    sa.Column('durability', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modification_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('effect', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('special_trait_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('effect', sa.String(length=200), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weapon_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('noise', sa.Integer(), nullable=True),
    sa.Column('ammo', sa.String(length=50), nullable=True),
    sa.Column('range', sa.Integer(), nullable=True),
    sa.Column('ergonomics', sa.Integer(), nullable=True),
    sa.Column('burst', sa.String(length=10), nullable=True),
    sa.Column('damage', sa.Integer(), nullable=True),
    sa.Column('durability', sa.Integer(), nullable=True),
    sa.Column('fire_rate', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('caliber', sa.String(length=20), nullable=True),
    sa.Column('magazine_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lobby_armor_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lobby_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_durability', sa.Integer(), nullable=True),
    sa.Column('material', sa.String(length=50), nullable=True),
    sa.Column('movement_penalty', sa.Integer(), nullable=True),
    sa.Column('container_slots', sa.Integer(), nullable=True),
    sa.Column('protection', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lobby_artifact_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lobby_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('effect', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lobby_background_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lobby_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('pluses', sa.Text(), nullable=True),
    sa.Column('minuses', sa.Text(), nullable=True),
    sa.Column('skill_bonuses', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lobby_backpack_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lobby_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lobby_consumable_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lobby_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('effect', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lobby_container_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lobby_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('effect', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lobby_crafting_material_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lobby_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lobby_detector_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lobby_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lobby_effect_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lobby_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lobby_gas_mask_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lobby_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_durability', sa.Integer(), nullable=True),
    sa.Column('filter_capacity', sa.Integer(), nullable=True),
    sa.Column('material', sa.String(length=50), nullable=True),
    sa.Column('accuracy_penalty', sa.Integer(), nullable=True),
    sa.Column('ergonomics_penalty', sa.Integer(), nullable=True),
    sa.Column('charisma_bonus', sa.Integer(), nullable=True),
    sa.Column('protection', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lobby_helmet_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lobby_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_durability', sa.Integer(), nullable=True),
    sa.Column('material', sa.String(length=50), nullable=True),
    sa.Column('accuracy_penalty', sa.Integer(), nullable=True),
    sa.Column('ergonomics_penalty', sa.Integer(), nullable=True),
    sa.Column('charisma_bonus', sa.Integer(), nullable=True),
    sa.Column('protection', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lobby_melee_weapon_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lobby_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('damage', sa.Integer(), nullable=True),
    sa.Column('durability', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lobby_modification_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lobby_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('effect', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lobby_organization_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lobby_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lobby_special_trait_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lobby_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('effect', sa.String(length=200), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lobby_weapon_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lobby_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('noise', sa.Integer(), nullable=True),
    sa.Column('ammo', sa.String(length=50), nullable=True),
    sa.Column('range', sa.Integer(), nullable=True),
    sa.Column('ergonomics', sa.Integer(), nullable=True),
    sa.Column('burst', sa.String(length=10), nullable=True),
    sa.Column('damage', sa.Integer(), nullable=True),
    sa.Column('durability', sa.Integer(), nullable=True),
    sa.Column('fire_rate', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('caliber', sa.String(length=20), nullable=True),
    sa.Column('magazine_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lobby_weapon_templates')
    op.drop_table('lobby_special_trait_templates')
    op.drop_table('lobby_organization_templates')
    op.drop_table('lobby_modification_templates')
    op.drop_table('lobby_melee_weapon_templates')
    op.drop_table('lobby_helmet_templates')
    op.drop_table('lobby_gas_mask_templates')
    op.drop_table('lobby_effect_templates')
    op.drop_table('lobby_detector_templates')
    op.drop_table('lobby_crafting_material_templates')
    op.drop_table('lobby_container_templates')
    op.drop_table('lobby_consumable_templates')
    op.drop_table('lobby_backpack_templates')
    op.drop_table('lobby_background_templates')
    op.drop_table('lobby_artifact_templates')
    op.drop_table('lobby_armor_templates')
    op.drop_table('weapon_templates')
    op.drop_table('special_trait_templates')
    op.drop_table('organization_templates')
    op.drop_table('modification_templates')
    op.drop_table('melee_weapon_templates')
    op.drop_table('helmet_templates')
    op.drop_table('gas_mask_templates')
    op.drop_table('effect_templates')
    op.drop_table('detector_templates')
    op.drop_table('crafting_material_templates')
    op.drop_table('container_templates')
    op.drop_table('consumable_templates')
    op.drop_table('backpack_templates')
    op.drop_table('background_templates')
    op.drop_table('artifact_templates')
    op.drop_table('armor_templates')
    # ### end Alembic commands ###
