"""add weather

Revision ID: f60d114a4ae4
Revises: 149843612790
Create Date: 2026-03-04 19:34:04.107804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60d114a4ae4'
down_revision = '149843612790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lobbies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weather_settings', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lobbies', schema=None) as batch_op:
        batch_op.drop_column('weather_settings')

    # ### end Alembic commands ###
